### ISSUE TITLE
Fail to down an artifact previously uploaded by `actions/upload-artifact`

### ISSUE THREAD

**Issue by tarcila** [actions/download-artifact#12]
Hi,

I am discovering gh actions, and am running into an issue with artifacts. When trying to download a specific artifact, it fails with the following message:
```
##[warning]Fail to download 'test/installed/x64-linux/share/Catch2/gdbinit', error: Could not find a part of the path '/home/runner/work/gha-download-bug/gha-download-bug/test/installed/x64-linux/share/Catch2/gdbinit'. (Downloader 1)
##[warning]Back off 25.301 seconds before retry. (Downloader 1)
##[warning]Fail to download 'test/installed/x64-linux/share/Catch2/lldbinit', error: Could not find a part of the path '/home/runner/work/gha-download-bug/gha-download-bug/test/installed/x64-linux/share/Catch2/lldbinit'. (Downloader 0)
##[warning]Back off 22.004 seconds before retry. (Downloader 0)
```
Not sure what makes this artifact problematic. For a reproducer, see:
- https://github.com/tarcila/gha-download-bug/blob/master/.github/workflows/main.yml
- https://github.com/tarcila/gha-download-bug/commit/6bbbae015b08a10df40682ed34ee89e03f2125dc/checks?check_suite_id=289179982
- https://github.com/tarcila/gha-download-bug

**Comment by lkillgore** [comment]
Hi @tarcila, the bug is due to the fact that there are two folders both with files different only in their casing:
`/installed/x64-linux/share/Catch2`
`/installed/x64-linux/share/catch2`

It seems that the download-artifact action is creating only one of the folders thinking the other one is the same.  We're looking into how best fix this issue.

**Comment by tarcila** [comment]
@lkillgore Thanks for the update! This casing issue is also the conclusion I came too and worked around my side. Looking forward to a fix!

**Comment by yacaovsnc** [comment]
Artifacts are stored case-insensitively - I don't think we can change this behavior now or it will break many others.  However, I also don't see any mention of this in our [docs](https://docs.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts#sharing-data-between-workflow-runs).  

I believe a change was made where we could first create the folder if it doesn't exist, so this particular issue is working now.  However in general we can not guarantee the correctness of artifacts that have file names differ in cases.  

We should fix our docs and mention this behavior explicitly.

**Comment by konradpabjan** [comment]
I ran some tests using the the provided repo: https://github.com/tarcila/gha-download-bug

It looks like this issue was fixed with the `v2` version `download-artifact` 😃 

I changed the following snippet in the YAML

```
    - uses: actions/download-artifact@v2
      with:
        name: test
        path: test-dir
```

And then I installed and ran the `tree` command to see the directory structure of everything and the files that were missing are now there: https://github.com/konradpabjan/gha-download-bug/runs/928418566?check_suite_focus=true

![image](https://user-images.githubusercontent.com/16109154/88946144-2fa94480-d28f-11ea-93ee-8521a80a5226.png)

However.... there is still a problem. If you try to download the artifact from the UI with the `zip` file. It's not there. So there is an issue when the artifact is getting packaged together for download

**Comment by konradpabjan** [comment]
Uploads are case insensitive and after some internal evaluations we won't be addressing this issue.

This behavior has been documented in both `upload-artifact` and `download-artifact`
https://github.com/actions/download-artifact#limitations
https://github.com/actions/upload-artifact#limitations

On the `upload-artifact` side, the action will detect files that will be overwritten because of case insensitivity but the action will not fail.

If case sensitivity is required, you can use `tar` beforehand
https://github.com/actions/download-artifact#maintaining-file-permissions-and-case-sensitive-files
