### ISSUE TITLE
[bug] Unable to download the artifact: Error: Unexpected http 404 during download

### ISSUE THREAD

**Issue by AllanOricil** [actions/download-artifact#140]
### What happened?

Action failed because it could not connect to github services to download an artifact. This never happened before. Probably some sort of instability, but this should never happen. Github Actions should retry up to N times before throwing an exception and killing the action.

![Screenshot_20211215-194007_Opera](https://user-images.githubusercontent.com/55927613/146276296-0bd70eb4-156b-46ea-acf6-9d8b6affc9c3.jpg)

### What did you expect to happen?

Artifact should be downloaded and if it fails this action should retry up to N times

### How can we reproduce it?

No idea

### Anything else we need to know?

This issue was addressed here before: https://github.com/actions/runner/issues/1559

### What version of the action are you using?

v2

### What are your runner environments?

linux

**Comment by webknjaz** [comment]
I've been observing this happening more often over the past months. Here's one example: https://github.com/ansible/pylibssh/actions/runs/3457781252/jobs/5771562788#step:10:39.
```console
  with:
    name: python-package-distributions
    path: dist/
  env:
    FORCE_COLOR: 1
    MYPY_FORCE_COLOR: 1
    PIP_DISABLE_PIP_VERSION_CHECK: 1
    PIP_NO_PYTHON_VERSION_WARNING: 1
    PIP_NO_WARN_SCRIPT_LOCATION: 1
    PY_COLORS: 1
    TOX_PARALLEL_NO_SPINNER: 1
    TOX_TESTENV_PASSENV: FORCE_COLOR MYPY_FORCE_COLOR NO_COLOR PY_COLORS PYTEST_THEME PYTEST_THEME_MODE
/usr/bin/docker exec  8e9b4b3a3e215104851b43b30366407e08d2a9f8389765f54f8b6d27543ca572 sh -c "cat /etc/*release | grep ^ID"
Starting download for python-package-distributions
Directory structure has been setup for the artifact
Total number of files that will be downloaded: 22
##### Begin Diagnostic HTTP information #####
Status Code: 404
Status Message: Not Found
Header Information: {
  "cache-control": "no-store,no-cache",
  "pragma": "no-cache",
  "content-length": "348",
  "content-type": "application/json; charset=utf-8",
  "strict-transport-security": "max-age=2592000",
  "x-tfs-processid": "389d9ec2-c23f-4037-8127-c98f0d1ca9a4",
  "activityid": "00b3aec5-2609-4e99-89c0-8a6891e283fd",
  "x-tfs-session": "00b3aec5-2609-4e99-89c0-8a6891e283fd",
  "x-vss-e2eid": "00b3aec5-2609-4e99-89c0-8a6891e283fd",
  "x-vss-senderdeploymentid": "d624195d-30e0-1768-06a5-b10a7879c7db",
  "x-frame-options": "SAMEORIGIN",
  "x-cache": "CONFIG_NOCACHE",
  "x-msedge-ref": "Ref A: F2F7ACB826C748718703AE4A10361DAD Ref B: BN3EDGE0517 Ref C: 2022-11-14T01:17:58Z",
  "date": "Mon, 14 Nov 2022 01:17:57 GMT"
}
###### End Diagnostic HTTP information ######
Error: Unable to download the artifact: Error: Unexpected http 404 during download for https://pipelines.actions.githubusercontent.com/cC5s7csFV8PcrlweNRWx6PDHHyvYCGGwuLa0yo6ROPMTVelxBD/_apis/resources/Containers/27789930?itemPath=python-package-distributions%2Fansible_pylibssh-1.0.1a2.dev25%2Bgbf8194b-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
```

It seems like this is happening because of GitHub's eventual consistency and race conditions. In my case, this workflow only cares about one `.tar.gz` file that is already there. But there are other jobs that add new `.whl` files and upload them there. Those jobs run in parallel (asynchronously, really) with the one that fails to complete the download.
It appears like one of those other jobs added a `ansible_pylibssh-1.0.1a2.dev25+gbf8194b-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl` file. So the API was returning it in the list of the files present in the artifact:
```console
Total number of files that will be downloaded: 22
```
But the CDN's cache hasn't yet caught up with that and hasn't made that file available, effectively causing the HTTP 404 Not Found error. So here we are: the file exists, but at the same time it doesn't.

I followed the code path and discovered the following:
1. Code in this repository is just a faced calling an externally implemented `downloadArtifact()` function at https://github.com/actions/download-artifact/blob/9782bd6/src/download-artifact.ts#L43-L47.
2. That external library has retries implemented but the check at https://github.com/actions/toolkit/blob/b36e70495fbee083eb20f600eafa9091d832577d/packages/artifact/src/internal/download-http-client.ts#L268 does not account for 404 Not Found
3. The list of retriable HTTP codes https://github.com/actions/toolkit/blob/b36e70495fbee083eb20f600eafa9091d832577d/packages/artifact/src/internal/utils.ts#L74-L81 does not include `HttpCodes.NotFound` from https://github.com/actions/toolkit/blob/b36e70495fbee083eb20f600eafa9091d832577d/packages/http-client/src/index.ts#L25.
4. In normal circumstances, that'd be alright, since the HTTP 4xx range represents client/user errors. But with the race conditions and failures to populate the CDN cache we're seeing now, it'd be reasonable to add retries on 404 here too, since the previous API call has already announced that it's expected for this file to appear at some point.
5. Another solution would be to tweak GitHub's back-end to only advertise files that are already delivered across the CDN.

@konradpabjan @rentziass @yacaovsnc @jtamsut @thboop @robherley could you take a look at this? It adds a lot of friction, but seems quite easy to fix.
