### ISSUE TITLE
[feat req] glob based name for multiple artifacts

### ISSUE THREAD

**Issue by y-nk** [actions/download-artifact#214]
### What would you like to be added?

The ability to download multiple artifacts based on a glob, at once.

for example:

```
with:
  name: test-runner-*-reports
```

would be nice. not sure how much of this is possible tho.

thanks a lot for the consideration.

### Why is this needed?

I'm using a matrix of tests to upload their results, since we can't rely on job outputs in matrix, and i'd like a shorthand way to download all the reports at once.

**Comment by leleliu008** [comment]
maybe a new github action named `actions/download-artifacts` would be nice to do what `https://cli.github.com/manual/gh_run_download` does.

we need this beacuse `gh run download` can't download artifacts from current run. https://github.com/cli/cli/issues/5625

**Comment by brianjmurrell** [comment]
I wonder how many more tickets are going to be opened for this functionality.  There's probably half-a-dozen of them currently and probably more will be added.

**Comment by y-nk** [comment]
@brianjmurrell feel free to close and mark as duplicate. some popular repo even pin the most popular issues to grant more visibility.

**Comment by brianjmurrell** [comment]
The question becomes which should be the master issue for the missing functionality that all of the others should be duplicates of.  I don't have a grasp of which issue best captures the issue and solutions to become the master ticket and the rest become duplicates.

That said, this is sorely needed functionality.  :smile:

**Comment by y-nk** [comment]
@brianjmurrell "usually" in other repos, the master issue is the one matching most of those criterias:

- the 1st one created
- the best documented
- the most popular/followed

not sure mine ticks any of those 😂

**Comment by per1234** [comment]
Since the existence of multiple issues was discussed here, I'll add a list of the open issues I found in order to create linkbacks between them so that all relevant discussion can be found more easily (and maybe to help with the closure of some of them as duplicates):

- https://github.com/actions/download-artifact/issues/6
- https://github.com/actions/download-artifact/issues/103
- https://github.com/actions/download-artifact/issues/165

**Comment by staticdev** [comment]
This feature is especially relevant now with v4, since when you upload you cannot have repeated names. In my case I upload various test result files and docs. When I download, I need to download only the test results to combine them and get coverage. Today I download all as a workaround to make it simple.

**Comment by vmjoseph** [comment]
Closed with the merging of https://github.com/actions/download-artifact/pull/259
