### ISSUE TITLE
[bug] Downloading a artifact once removes it from the listing

### ISSUE THREAD

**Issue by Shurtu-gal** [actions/download-artifact#369]
### What happened?

We have a workflow where we upload a artifact only once, and then reuse the same artifact multiple times. However now after downloading the artifact in first job it is not working again.

Workflow run: https://github.com/asyncapi/cli/actions/runs/12433974373
Workflow file: https://github.com/asyncapi/cli/blob/master/.github/workflows/test-action.yml

### What did you expect to happen?

Although [breaking changes](https://github.com/actions/upload-artifact/blob/main/README.md#breaking-changes) mentions that multiple uploads to same artifact is not possible download should not be any problem.

### How can we reproduce it?

Workflow run: https://github.com/asyncapi/cli/actions/runs/12433974373
Workflow file: https://github.com/asyncapi/cli/blob/master/.github/workflows/test-action.yml

### What version of the action are you using?

v4

### What are your runner environments?

linux

### Are you on GitHub Enterprise Server? If so, what version?

No

**Comment by IITI-tushar** [comment]
Hi @Shurtu-gal, I think in the workflow run https://github.com/asyncapi/cli/actions/runs/12433974373
![image](https://github.com/user-attachments/assets/58d15a5b-1275-4d7a-bc08-67a94a7805ec)

artifact did not get downloaded maybe because of in this PR [1601](https://github.com/asyncapi/cli/pull/1601)
![image](https://github.com/user-attachments/assets/834bf9eb-4347-4d9c-a12a-e16ffe2cb1d1)

this changes with download artifact don't match as given in [MIGRATION.md](https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md) 

this is from migration.md
![image](https://github.com/user-attachments/assets/d239bdc0-4b5f-470d-afa9-11be16a3890a)

**Comment by Shurtu-gal** [comment]
I am aware of the PR causing the issue and I don't believe this will resolve it.
