### ISSUE TITLE
Retry on ETIMEDOUT

### ISSUE THREAD

**Issue by Yuri6037** [actions/download-artifact#49]
Randomly, rarely this action has a chance to throw ETIMEDOUT and crash the entire build. Currently this happened exactly once here: https://github.com/BlockProject3D/Framework/pull/95/checks?check_run_id=912239366.
The affected OS is for now limited to OSX.

```
Run actions/download-artifact@v2
1m 16s
##[error]connect ETIMEDOUT 13.107.42.16:443
Run actions/download-artifact@v2
Starting download for Snapshot-macos-latest-Debug-x64
##[error]connect ETIMEDOUT 13.107.42.16:443
```

**Comment by konradpabjan** [comment]
I looked at our internal telemetry, and this actually isn't an issue with `download-artifact`. The hosted runner abruptly disconnected. It happens very sporadically, a little bit more often on Mac.

We have an internal issue tracking this bug already, so I've added this issue to the report and notified the appropriate engineers. Since this isn't `download-artifact` specific (this abrupt disconnection can happen with any action), I'll go ahead and close this out since there is nothing we can do. I recommend following this issue: https://github.com/actions/virtual-environments/issues/736 as other customers are reporting similar issues with hosted Mac.
