### ISSUE TITLE
Document permissions loss on linux

### ISSUE THREAD

**Issue by software-opal** [actions/download-artifact#9]
I was trying to pass a compiled executable from one job to another only to find it was no longer executable. I understand that under the hood zip files are used, but it would have been nice to have some sort of warning to say that you will loose all the permissions once they go through the upload/download cycle.

**Comment by PHLAK** [comment]
I also noticed this as well. Artifact permissions need to remain intact.

**Comment by konradpabjan** [comment]
Both `upload-artifact` and `download-artifact` got small `README` updates to document permission loss: https://github.com/actions/download-artifact#limitations
https://github.com/actions/upload-artifact#limitations

Permission loss is an issue on the upload side and there are some open issues in `upload-artifact`  so I'm closing out this issue: https://github.com/actions/upload-artifact/issues?q=is%3Aissue+is%3Aopen+label%3A%22Artifact+Permissions%22

**Comment by PHLAK** [comment]
While this is an acceptable work around I don't feel that this has been properly addressed. Why can't these actions preserve permissions? Having to even think about this is aggravating and is one of the top reasons I don't use GitHub Actions.

**Comment by konradpabjan** [comment]
You can create a `tar` beforehand and upload that: https://github.com/actions/download-artifact#maintaining-file-permissions-and-case-sensitive-files

When you download from the `UI` you will have a zip of a tar which is a little bit annoying, and using `actions/download-aritfact` you will have to un-tar everyhing post download, but it is possible to maintain file permissions.

This issue was only for documenting the permission loss, there is another issue to actually maintain file permissions: https://github.com/actions/download-artifact/issues/14
